apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{include "oddsbender-scrapers.fullname" .}}-scraper-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{.Values.secretStore.secretName}}
        objectType: secretsmanager
        jmesPath: 
          - path: postgres_password
            objectAlias: postgres_password
          - path: redis_pass
            objectAlias: redis_pass
          - path: rabbitmq_password
            objectAlias: amqp_password
  secretObjects:
    - data:
      - key: postgres_password
        objectName: postgres_password
      - key: redis_pass
        objectName: redis_pass
      - key: amqp_password
        objectName: amqp_password
      secretName: {{include "oddsbender-scrapers.fullname" .}}-scraper-secret-config
      type: Opaque