apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scale-deployments
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["apps"]
    resources:
      - deployments
      - deployments/scale
      - statefulsets
      - statefulsets/scale
      - pods
    verbs:
      - patch
      - get
      - list
  - apiGroups: ["*"]
    resources:
      - pods
    verbs:
      - get
      - list
      - delete