apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-scaler
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "oddsbender-scrapers.serviceAccountName" . }}-game-scheduler 
roleRef:
  kind: Role
  name: scale-deployments
  apiGroup: rbac.authorization.k8s.io