{{- if .Values.gameScheduler.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oddsbender-scrapers.serviceAccountName" . }}-game-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oddsbender-scrapers.labels" . | nindent 4 }}
  {{- with .Values.gameScheduler.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}