{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oddsbender-scrapers.serviceAccountName" . }}
  labels:
    {{- include "oddsbender-scrapers.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 4 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: oddsbender-sa-role
rules:
  - apiGroups:
      - ""
      - apps
    resources:
      - deployments
      - statefulsets
    verbs: 
      - get
      - list
      - watch
      - create
      - update
      - patch 
      - delete 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oddsbender-sa-rolebinding
  namespace: {{ .Release.Namespace}} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oddsbender-sa-role
subjects:
- namespace: {{ .Release.Namespace}}  
  kind: ServiceAccount
  name: {{ include "oddsbender-scrapers.serviceAccountName" . }}
{{- end }}
