apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oddsbender-scrapers.fullname" . }}-script-configmap
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "scripts/scale_deployments.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "scripts/cleanup_pods.sh").AsConfig | indent 2 }}